### ISSUE TITLE
User content isn't loading in all places

### ISSUE THREAD

**Issue by AMShegstad** [DevynJohnson/project1#29]
The name, reading goal, and books left to read are still unpopulated.

**Comment by DevynJohnson** [comment]
I wasn't able to merge the changes I had made for those - I will work on reincorporating them today. It will be easier to add those in again than it was to try to navigate all of the merge conflicts I had with my code and the changes we have to the style.

**Comment by DevynJohnson** [comment]
Issue is resolved with the latest PR.
