### ISSUE TITLE
Aside is cut off when viewed on my laptop screen

### ISSUE THREAD

**Issue by DevynJohnson** [DevynJohnson/project1#33]
When viewed on my monitor there is no issue, but my laptop screen at 741px cuts off the bottom of the aside just below the To Be Read: text. I cannot access the buttons that are below that or see the content of the To Be Read section.

**Comment by AMShegstad** [comment]
Can we remove the padding from the top of the aside?

**Comment by DevynJohnson** [comment]
Even just reducing it might help - we may want to leave a small amount of padding to keep the content from being too close to the navbar.

**Comment by AMShegstad** [comment]
[like]  Alexander Shegstad reacted to your message:
________________________________

**Comment by DevynJohnson** [comment]
Reducing the top padding alone didn't free up enough space. I tried changing the text in the book goal box from h2 to h4 to see if smaller text might help but I'm still cut off - I'll play around with it tomorrow to see what I can figure out.

**Comment by DevynJohnson** [comment]
Issue was on my end
